project:
  type: website

website:
  title: "Oliver Maith"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: cv.qmd
        text: "CV"
      - research.qmd
      - publications.qmd
  back-to-top-navigation: true
  page-footer: 
    center: "© 2024 Oliver Maith"
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true



# icons:
# https://github.com/quarto-ext/fontawesome
# https://github.com/schochastics/academicons